---
# TMSetup Variables (non-configurable)
tmsetup_tm_version: '0.4.0-pre'
tmsetup_go2rtc_version: 'v1.8.5'
tmsetup_frigate_version: '0.15.1'
tmsetup_node_red_tm_version: '4.0.9'

tmsetup_remove_packages:
  - rpicam-apps-lite

tmsetup_packages:
  - aptitude
  - ca-certificates
  - host
  - screen
  - build-essential
  - cron
  - rpicam-apps

tmsetup_base_required_facts:
  - 'os_family'
  - 'distribution'
  - 'distribution_major_version'
  - 'distribution_version'
  - 'architecture'
  - 'user_id'
  - 'user_dir'
  - 'hostname'

...
