---
# tmsetup variables (non-configurable)
tmsetup_tm_version: '0.3.0'
tmsetup_go2rtc_version: 'v1.8.5'
tmsetup_frigate_version: '0.14.0'

tmsetup_packages:
  - ca-certificates
  - host
  - screen
  - build-essential
  - cron

tmsetup_base_required_facts:
  - 'ansible_os_family'
  - 'ansible_distribution'
  - 'ansible_distribution_major_version'
  - 'ansible_distribution_version'
  - 'ansible_architecture'
  - 'ansible_user_id'
  - 'ansible_user_dir'

...
